# Generated by Django 4.2.3 on 2023-07-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "accompagnements",
                    models.ManyToManyField(blank=True, to="materiels.materiel"),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiels_achetes",
                        to="materiels.enseignant",
                    ),
                ),
                (
                    "possesseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiels_possedes",
                        to="materiels.enseignant",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materiels.salle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangementPossesseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lieu", models.CharField(max_length=100)),
                ("occasion", models.CharField(max_length=100)),
                ("objectif_utilisation", models.TextField()),
                (
                    "ancien_possesseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chgmt_possesseur_ancien",
                        to="materiels.enseignant",
                    ),
                ),
                (
                    "materiel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materiels.materiel",
                    ),
                ),
                (
                    "nouveau_possesseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chgmt_possesseur_nouveau",
                        to="materiels.enseignant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accessoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("etat", models.CharField(max_length=100)),
                (
                    "materiels",
                    models.ManyToManyField(
                        related_name="accessoires", to="materiels.materiel"
                    ),
                ),
            ],
        ),
    ]
