# Generated by Django 4.2.3 on 2023-07-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiel",
            name="salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiels_salle_num",
                to="materiels.salle",
            ),
        ),
    ]
