# Generated by Django 4.2.3 on 2023-07-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0003_alter_materiel_salle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materiel",
            name="budget",
        ),
        migrations.AddField(
            model_name="materiel",
            name="budget_annuel",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="materiel",
            name="budget_financements_exceptionnels",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="materiel",
            name="budget_projets",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="materiel",
            name="mandant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiels_mandates",
                to="materiels.enseignant",
            ),
        ),
        migrations.AlterField(
            model_name="materiel",
            name="salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiels_salle_num",
                to="materiels.salle",
            ),
        ),
    ]
