# Generated by Django 4.2.3 on 2023-07-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0005_materiel_proprietaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiel",
            name="proprietaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiels_propriete",
                to="materiels.enseignant",
            ),
        ),
    ]
