# Generated by Django 4.2.3 on 2023-07-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0006_alter_materiel_proprietaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignant",
            name="prenom",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
