# Generated by Django 4.2.3 on 2023-07-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0008_alter_enseignant_prenom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enseignant",
            name="prenom",
            field=models.CharField(max_length=50),
        ),
    ]
