# Generated by Django 4.2.3 on 2023-07-05 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0009_alter_enseignant_prenom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enseignant",
            name="prenom",
        ),
    ]
