# Generated by Django 4.2.3 on 2023-07-06 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0011_changementpossesseur_accessoires_present_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changementpossesseur",
            name="accessoires_present",
        ),
        migrations.RemoveField(
            model_name="changementpossesseur",
            name="etat_accessoires",
        ),
    ]
