# Generated by Django 4.2.3 on 2023-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0012_remove_changementpossesseur_accessoires_present_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changementpossesseur",
            name="accessoires_presents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="changementpossesseur",
            name="etat",
            field=models.TextField(blank=True, null=True),
        ),
    ]
