# Generated by Django 4.2.3 on 2023-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0013_changementpossesseur_accessoires_presents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessoire",
            name="etat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
