# Generated by Django 4.2.3 on 2023-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materiels", "0016_etataccessoire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="EtatAccessoire",
        ),
    ]
